### ISSUE TITLE
Add a website?

### ISSUE THREAD

**Issue by ghost** [djedi/DailyNotes#15]
Can you maybe make a website instead of the current method?

Spoiler alert i really want it!

**Comment by m0ngr31** [comment]
You mean instead of self hosting it, I host it for you?

**Comment by ghost** [comment]
Yes, For example: you type the link and the first thing that appears is a login page, then you put your credentials and login taking you to the actual thing that this repo is about. And i know that hosting a website ain't cheap but i would really like it has a website.
I also have another idea witch consists of creating an installer like .exe for windows and etc for others OS's.

**Comment by m0ngr31** [comment]
I have no intention of hosting it publicly at this time.
