### ISSUE TITLE
[Request] Autosave

### ISSUE THREAD

**Issue by caillou** [djedi/DailyNotes#23]
# Motivation

Using DailyNotes quickly becomes a second nature. Yet, I often forget to hit that save button, and loose information.

Up until now, I have used Apple Notes, which automatically save. It has proven to be the right workflow for me. Offering this as an option would be brilliant.

**Comment by m0ngr31** [comment]
That's a great idea. I'll add this.

**Comment by djedi** [comment]
https://github.com/m0ngr31/DailyNotes/pull/47

**Comment by m0ngr31** [comment]
Done on #48
