### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by AlexKalopsia** [djedi/DailyNotes#3]
Firt of all, thanks for making DailyNotes. The project looks exactly like what I was looking for, and I love how easy everything was in terms of setup. I am running in a Docker container, zero issues whatsoever.

I have a few questions:

1. From the screenshots it looks like I'm potentially running an old version of DailyNotes. I can't see the checkbox icon next to the "+". Is this because the docker hub version is not up to date?
2. I currently found the note creation a bit confusing. I understand now - after using the tool a bit - that I can have 1 note per day, and I can also create notes that are not date-bound. This was really unclear at the beginning as I thought you could create more than one note per day and visualize them by clicking on the date. I guess that the name of the tool itself, Daily Notes, gave me this impression and expectation. I don't have a clear suggestion, but my gut feeling is that `Notes` (the non-date bound) should be called something different, always be visible in the sidebar, and the "+" sign should be next to it (rather than on the main top bar). 
3.  Could you clarify the design difference between Tags and Projects? When do you imagine users using one rather than the other?

That's it, thank you again for making DailyNotes, the tool is super promising, hope I'll find a way to contribute somehow

A.

**Comment by m0ngr31** [comment]
Hey Alex,

Sorry I haven't been getting notified on GH notifications for some reason.

1. Yeah, you're on an older version. The docker hub should auto update though, so you should just need to pull the latest.
2. Yes, there is only 1 "note" per day, but a regular note is a separate entity. I do like your suggestion about having the plus bar in the sidebar. I'll have to give that some consideration.
3. I build this primarily for myself so it was nice to be able to have multiple meta fields I could filter against.
