### ISSUE TITLE
!docker

### ISSUE THREAD

**Issue by ithakaa** [djedi/DailyNotes#35]
Asking if we can get instructions on installing without docker please

Would be greatly appreciated

**Comment by chrispratl** [comment]
Just mimic what the docker file does:

* Install gunicorn as WSGI server (`pip install gunicorn`)
* Install the other pip requirements (`pip install -r requirements.txt`)
* Install node-sass (`cd client && npm install node-sass`)
* Prepare the app (`npm ci && npm rund build`)
* Run the prepared startup script (`sh run.sh` for example)
