### ISSUE TITLE
Pulled latest from Docker Hub. Seems out of date?

### ISSUE THREAD

**Issue by bkuhns** [djedi/DailyNotes#41]
I pulled `m0ngr31/dailynotes:latest` but I'm missing the checkbox icon next to the plus button at the top and I don't see any options for searching. I feel like I'm on an older version but I don't know how else to force something newer?

**Comment by m0ngr31** [comment]
The tasks icon will only show up if it can detect that you have tasks in your notes. The search page will show up if you click on a tag or a project.
