### ISSUE TITLE
Export?

### ISSUE THREAD

**Issue by TheNomad11** [djedi/DailyNotes#44]
Very beautiful app! I understand that it still is in beta, so features will be added. In the roadmap, I did not see any export option. Would be useful to have, I think?

**Comment by m0ngr31** [comment]
I'll add it to the roadmap

**Comment by djedi** [comment]
https://github.com/m0ngr31/DailyNotes/pull/59

**Comment by m0ngr31** [comment]
Fixed on v1.0-beta14. Thanks @djedi!
