### ISSUE TITLE
BaseUrl for reverse proxy

### ISSUE THREAD

**Issue by vbuzzano** [djedi/DailyNotes#6]
Hello, 

I realy like your project and the idea of dailynotes

would it be possible to add environment variable for BASE URL to be able run dailynotes behind a reverse proxy subfolder ?

eg
https://mydomain.ex/subfolder/date/09-26-2020

Thank you

**Comment by m0ngr31** [comment]
That should be relatively simple to do. I'll take a look at this.

**Comment by m0ngr31** [comment]
Done on #48

**Comment by lawlient** [comment]
Hi, looks like the variable BASE_URL only works at  "npm run build", it doesn't work if build has done
