### ISSUE TITLE
sqalchemy errors ; stuck on sign up page

### ISSUE THREAD

**Issue by bugsbunny88** [djedi/DailyNotes#66]
I have a bunch of python sqalchemy errors when installing this ; on Docker Synology using portainer ; it was a simple enough guie I was following . stuck at sign up page . [https://mariushosting.com/how-to-install-dailynotes-on-your-synology-nas/]

`sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
today at 6:57:58 PM(Background on this error at: https://sqlalche.me/e/14/e3q8)`

I have extracted what I feel might be the most relevant code out of the logs ... 
![image](https://user-images.githubusercontent.com/24847798/148666534-91d907cf-2e4a-4ea8-9c7e-c91cc18bb3f1.png)

**Comment by m0ngr31** [comment]
Seems like it's not reading the DB file. It could be one of a few things...

1. The config folder isn't being passed through properly. So double check that.
2. There is an issue with the file permissions and that's something I need to get figured out since it has issues on some installs.

**Comment by bugsbunny88** [comment]
its not #1 ; i've done environment variables version with  PUIG/PGID to no avail ; its something permissions related at creation because the dailynotes folder is empty even after the container is running . I think the .db file isn't being generated at the onset due to the permission issue .

**Comment by m0ngr31** [comment]
Try using the tag `v1.0-beta10` on docker. That was the version before the permissions.

**Comment by bugsbunny88** [comment]
perfect ; yup I am in now ; works . I will just stick to this tag and keep tabs on this thread for when I can move forward with an update. Atleast I'm up and running ! thanks man

**Comment by kartikay-bagla** [comment]
I have also been facing the same issue. While using `v1.0-beta10` worked for me, I don't think it has the search option, which would've been quite useful. 

Steps to reproduce:
1. run command provided in README for docker

Investigating the logs also showed that while the error is same, the root cause is that the `.env` file is not being opened due to a permission error. 

I have also tried running as root and passing in `PUID` and `GUID` for root to no avail.

**Comment by ItsSiem** [comment]
I have also run into this problem, I am however kind of new to docker. So how do I install an earlier version?
sorry for the noob question

**Comment by m0ngr31** [comment]
@bugsbunny88 @kartikay-bagla I reverted the changes for the permissions stuff on the latest docker image. Try it now.

**Comment by kartikay-bagla** [comment]
Getting this now.

```
ERROR: for dailynotes  Cannot start service dailynotes: unable to find user abc: no matching entries in passwd file
ERROR: Encountered errors while bringing up the project.
```

For context here's my `docker-compose.yml`

```
version: '3.1'
services:
  dailynotes:
    image: m0ngr31/dailynotes:latest
    restart: unless-stopped
    ports:
      - '20007:5000'
    volumes:
      - ./config:/app/config
```

**Comment by m0ngr31** [comment]
Good catch. I'm pushing up a fix

**Comment by kartikay-bagla** [comment]
Can you ping me once it's uploaded on dockerhub? I'll try it out.

**Comment by m0ngr31** [comment]
Try now

**Comment by kartikay-bagla** [comment]
Works like a charm now!

Thanks for helping out.
