### ISSUE TITLE
Text lost after marking a task complete

### ISSUE THREAD

**Issue by komish** [djedi/DailyNotes#87]
I don't know if I have enough details to help troubleshoot this, but I enabled autosave and started writing away.

Then I left the page up in a browser and did some other things. Came back to mark a task as completed and the page lost text that I had written earlier in the day. I was able to "undo" it and bring the text back, and I believe I hit save. After a page refresh, however, the text disappeared again and now I can't recover it.

I wish I had more to share, but the logs don't show anything other than benign warnings re: cache_key.

Otherwise, the project looks great. The UI is excellent.

**Comment by m0ngr31** [comment]
I'm not sure exactly what happened in your case, but I do think there is some weird issue with the Autosave feature (I don't use it myself). I'd have to play with it some to figure out what is going on.
